version: '3.8'

services:
  db:
    build: 
      context: ./db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
    volumes:
      - ./db/store:/var/lib/postgresql/data
    networks:
      - network
  server:
    build: 
      context: ./spring
      dockerfile: Dockerfile
    #restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/world
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: docker
      SPRING_DATASOURCE_DRIVER: org.postgresql.Driver  
    networks:
      - network

networks:
  network: